name: Deploy Cloud Workflow
on:
  push:
    branches:
      - main
      - development
    paths:
      - 'workflows/post-adjustments-workflow.yaml'
jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-18.04
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
    - name: 'Setup auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Use gcloud CLI
      run: |
        gcloud workflows deploy post-adjustments-workflow \
        --location {{ vars.GCP_REGION }} \
        --source post-adjustments-workflow.yaml \
        --project ${{ vars.GCP_PROJECT_ID }} \
        --labels "commit-sha=${{ github.sha }}" 