name: Deploy Cloud Workflow
on:
  push:
    branches:
      - main
      - development
    paths:
      - 'workflows/post-adjustments-workflow.yaml'
jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        export_default_credentials: true
    - name: Use gcloud CLI
      run: |
        gcloud workflows deploy post-adjustments-workflow \
        --location {{ vars.GCP_REGION }} \
        --source post-adjustments-workflow.yaml \
        --project ${{ vars.GCP_PROJECT_ID }} \
        --labels "commit-sha=${{ github.sha }}" 