name: Deploy Workflow Gateway Function

on:
  push:
    branches:
      - main
    paths:
      - 'cloud-function/api-gateway/**'
    
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v3'
    - name: 'Setup auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Verify gcloud CLI'
      run: 'gcloud info'
    - name: 'deploy function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'workflow_gateway'
        runtime: 'python39'
        region: ${{ secrets.GCP_REGION }}
        source: cloud-function/api-gateway 
        entry-point: workflow_gateway
        trigger: http
        
        
        

