name: Deploy Workflow Gateway Functions

on:
  push:
    branches:
      - staging
      - main
    paths:
      - 'cloud-function/api-gateway/**'
    
jobs:
  deploy_staging:
    runs-on: 'ubuntu-latest'
    environment: staging
    timeout-minutes: 30
    if: github.ref == 'refs/heads/staging'
    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v3'
    - name: Create .env file
      run: |
        echo "GCP_REGION=${{ vars.GCP_REGION }}" > cloud-function/api-gateway/.env
        echo "GCP_PROJECT=${{ vars.GCP_PROJECT_ID }}" >> cloud-function/api-gateway/.env
        cat cloud-function/api-gateway/.env
    - name: 'Setup auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'deploy Workflow Gateway function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'workflow_gateway'
        runtime: 'python39'
        region: '${{ vars.GCP_REGION }}'
        source_dir: cloud-function/api-gateway
        entry_point: workflow_gateway
  deploy_production:
    needs: deploy_staging
    runs-on: 'ubuntu-latest'
    environment: production
    timeout-minutes: 30
    if: github.ref == 'refs/heads/main'
    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v3'
    - name: Create .env file
      run: |
        echo "GCP_REGION=${{ vars.GCP_REGION }}" > cloud-function/api-gateway/.env
        echo "GCP_PROJECT=${{ vars.GCP_PROJECT_ID }}" >> cloud-function/api-gateway/.env
        cat cloud-function/api-gateway/.env
    - name: 'Setup auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'deploy Workflow Gateway function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'workflow_gateway'
        runtime: 'python39'
        region: '${{ vars.GCP_REGION }}'
        source_dir: cloud-function/api-gateway
        entry_point: workflow_gateway
      
        
