name: Deploy Workflow Gateway Function

on:
  push:
    branches:
      - main
    paths:
      - 'cloud-function/api-gateway/**'
    
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'


