name: Deploy Workflow Gateway Function

on:
  push:
    branches:
      - main
    paths:
      - 'cloud-function/api-gateway/**'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Cloud Function
      uses: GoogleCloudPlatform/github-actions/gcloud-cli@main
      with:
        args: functions deploy workflow_gateway --region=${{ secrets.GCP_REGION }} --source cloud-function/api-gateway --entry-point workflow_gateway --trigger-http --runtime python39 --no-allow-unauthenticated
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
